spring:
  application:
    name: demo-cloud-system-web
  profiles:
    active: single
feign:
  hystrix:
    enabled: true
hystrix: 
  command: 
    default: 
      execution: 
        timeout: 
          enabled: true
        isolation: 
          thread: 
            timeoutInMilliseconds: 30000
---
# 单机配置
spring:
  profiles: single
server:
  port: 8380
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/
---
# 节点一
spring:
  profiles: node1
server:
  port: 8381
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-node1:8761/eureka/,http://registry-node2:8762/eureka/,http://registry-node3:8763/eureka/
---
# 节点二
spring:
  profiles: node2
server:
  port: 8382
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-node1:8761/eureka/,http://registry-node2:8762/eureka/,http://registry-node3:8763/eureka/      
